### ISSUE TITLE
support diagnostic messages

### ISSUE THREAD

**Issue by mndrix** [fnogatz/tap#1]
It would be helpful to be able to [output diagnostics](https://metacpan.org/pod/Test::More#Diagnostics).  My inclination is to export `diag/1` (simple string argument) and `diag/2` (like format/2).  They'd be used like this:

``` prolog
'testing something' :-
    foo(X),
    diag("X = ~w", [X]),
    etc(X).
```

**Comment by nicoabie** [comment]
This is implemented based on the [examples](https://github.com/fnogatz/tap/blob/master/test/examples.pl)
but the `is_test_running` flag seems to be never true. so the messages do not appear.

@fnogatz tried to fix it but I don't know how to debug it :(

**Comment by fnogatz** [comment]
>  but the is_test_running flag seems to be never true. so the messages do not appear.

For me, this works as expected:

```sh
 make all
TAP version 13
1..3
ok 1 - simplest possible test case
ok 2 - simplest failing test case
# I'm a diagnostic message
ok 3 - generates a diagnostic message

# tests 3
# pass  3
```

So this `# I'm a diagnostic message` is missing when you run `make all`?

**Comment by nicoabie** [comment]
When I run make all the message appear but when I call it inside swipl or from the quickcheck library it does not.

```bash
[ngallinal@hxlm-ngallinal tap (master)]$ make all
TAP version 13
1..3
ok 1 - simplest possible test case
ok 2 - simplest failing test case
# I'm a diagnostic message
ok 3 - generates a diagnostic message

# tests 3
# pass  3

[ngallinal@hxlm-ngallinal tap (master)]$ swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 8.0.2)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- [test/examples].
true.

?- 'generates a diagnostic message'.
true.
```
Am I executing it in a way it is not supposed to?

**Comment by fnogatz** [comment]
This is as expected. `diag/2` behaves as no-op if not run in the context of TAP, as [documented (only) in the code](https://github.com/fnogatz/tap/blob/96553cbb42aea2526b0fd0ceb3bbf175a4a900aa/prolog/tap_raw.pl#L158-L172). `library(tap)` does not change the original clause:

```prolog
?- listing('generates a diagnostic message').
'generates a diagnostic message' :-
	diag("I'm a ~s message", ["diagnostic"]).
```

However, the term expander of `library(tap)` creates a `main/0` predicate that runs the actual test and prints the `diag/2` messages, as it is now in the context of TAP:

```prolog
?- listing(main).
:- dynamic main/0.

main :-
	tap_header(3),
	tap_call('simplest possible test case', state(1, 0), A),
	tap_call('simplest failing test case'(fail), A, B),
	tap_call('generates a diagnostic message', B, C),
	tap_footer(3, C).
true.

?- main.
TAP version 13
1..3
ok 1 - simplest possible test case
ok 2 - simplest failing test case
# I'm a diagnostic message
ok 3 - generates a diagnostic message

# tests 3
# pass  3
true.
```

If you want to run a single test in the context of TAP, there is `tap_call/1` to the rescue! :)

```prolog
?- tap_call('generates a diagnostic message').
# I'm a diagnostic message
ok 1 - generates a diagnostic message
true.
```

Is this what you would expect from `library(tap)`? Maybe some of this needs better documentation. I am very open to suggestions on how to improve.

**Comment by nicoabie** [comment]
Thanks @fnogatz! I confirm it is working as expected.
The only thing is that it does't work when loading the file from swipl, it does not generate the main.
```bash
[ngallinal@hxlm-ngallinal tap (master)]$ swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 8.0.2)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit http://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- [test/examples].
true.

?- listing(main).
:- dynamic main/0.


true.
```
But when calling it from the outside it works as expected.
```bash
[ngallinal@hxlm-ngallinal tap (master)]$ swipl -q -t main -s test/examples.pl 
TAP version 13
1..3
ok 1 - simplest possible test case
ok 2 - simplest failing test case
# I'm a diagnostic message
ok 3 - generates a diagnostic message

# tests 3
# pass  3
```
Thanks a lot for the time and explanation. If I found something else I'll let you now.

**Comment by fnogatz** [comment]
>  The only thing is that it does't work when loading the file from swipl, it does not generate the main.

Yeah, I also observed this. I think it is related to the `prolog_load_context/2` predicates in [`tap.pl`](https://github.com/fnogatz/tap/blob/96553cbb42aea2526b0fd0ceb3bbf175a4a900aa/prolog/tap.pl#L29-L36). Do you feel like fixing this? :)

**Comment by nicoabie** [comment]
Yeah, I'll give it a try! This issue can be closed now.
