### ISSUE TITLE
Catch error raised by library(quasi_quotations)

### ISSUE THREAD

**Issue by fnogatz** [fnogatz/tap#2]
I am using `library(tap)` to validate the structure generated by SWI-Prolog's [quasi-quotations](http://www.swi-prolog.org/pldoc/man?section=quasiquotations) and [DCGs](http://www.swi-prolog.org/pldoc/man?section=DCG). Unfortunately the error raised if a quasi-quotation could not be parsed is not catched by this library.

Any ideas how to catch the thrown error to produce the appropriate TAP output?
### Steps to reproduce

`test.pl`:

```
:- use_module(library(quasi_quotations)).
:- quasi_quotation_syntax(t).

a --> "a".

t(Content, _Args, _VariableNames, r) :-
    phrase_from_quasi_quotation(a, Content).

:- use_module(library(tap)).

'is valid' :-
  {|t||a|} = r.

'will raise an uncatched error' :-
  {|t||b|} = r.
```

Run command:

```
swipl -q -t main -f test.pl
```
### Experienced Result

```
ERROR: test.pl:15:6: Syntax error: quasi_quotation_parser_failed
TAP version 13
1..1
ok 1 - is valid
```
### Expected Result

```
TAP version 13
1..2
ok 1 - is valid
not ok 2 - will raise an uncatched error # fail
```

**Comment by mndrix** [comment]
Hi.  Unfortunately, `library(tap)` can't catch this error.  That's because the error, and all quasi-quotation expansion, happens at compile time.  The tests only execute at run time.  This is similar to how SWIPL handles other syntax errors.

You might be able to change your test code so that it tries reading a term with your quasi-quotation at run time.  In that case, `library(tap)` should do what you expect.  Good luck.

**Comment by fnogatz** [comment]
Hi Michael,

thanks for coming back to this. As you mentioned there seems to be no way to execute the quasi-quotation compilation at runtime. For the archive, here is my workaround to explicitly call the DCG instead with the help of `quote/2`:

```
:- use_module(library(quasi_quotations)).
:- quasi_quotation_syntax(t).

a(Res) -->
  "a",
  { Res = some(out) }.

t(Content, _Args, _VariableNames, Res) :-
    phrase_from_quasi_quotation(a(Res), Content).

quote(DCG,Input) :-
  string_codes(Input,Codes),
  phrase(DCG,Codes), !.

:- use_module(library(tap)).

'is valid' :-
  {|t||a|} == some(out).

'is valid II' :-
  quote(a(Res), "a"),
  Res == some(out).

'is not valid'(fail) :-
  quote(a(_Res), "b").
```

**Comment by mndrix** [comment]
Thanks @fnogatz for posting your results.  That will be very helpful for others who encounter the same problem.
